### PR TITLE
safeSearchAnnotaion has been added

### PR DESCRIPTION
**Pull request by imhafeez**

### CODE REVIEW

**Comment by faithoflifedev** [comment]
Hello @imhafeez , I've merged the code.  Would it be possible for you to supply a bare bones example so I can test your code?

Thanks.

**Comment by faithoflifedev** [comment]
Hi again @imhafeez , don't worry about providing the test code.  I was able to add the `safe-search` functionality to the `cli` portion of the package fairly easily and I used that for testing.  Other than a few spelling changes everything was good.

Thanks for your help with the project.  I've added you to the newly added list of contributors in the project README.

**Comment by faithoflifedev** [comment]
@imhafeez , v1.0.6 of the package has been published and it includes the changes referenced in your PR.

**Comment by imhafeez** [comment]
@faithoflifedev Thanks

**Pull request merged**
