### PR TITLE
Added support for textAnnotations & fullTextAnnotation

### PR DESCRIPTION
**Pull request by jluisrojas**
Added support for TEXT_DETECTION & DOCUMENT_TEXT_DETECTION features with images.

### CODE REVIEW

**Comment by faithoflifedev** [comment]
Is it possible for you to provide a short sample of example code for how to use this new functionality?  Maybe with a public domain test image?

**Comment by jluisrojas** [comment]
Yes sure, I will try to add this weekend an example with text detection to the example app.

**Comment by faithoflifedev** [comment]
Hi @JLuisRojas ,

I incorporated you PR and included some additional changes I had been planning to make.  When you get a chance, take a look at v1.0.7

**Comment by jluisrojas** [comment]
@faithoflifedev Thanks!

**Pull request merged**
